version: "3"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:delegated
      - /node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true